#ifndef __VDEC_DRV_IOC_H__
#define __VDEC_DRV_IOC_H__

#include "drv_ioc_extension.h"

#define IOC_TYPE_VDEC 'D'

typedef struct iocsendstream_t
{
    fyVDEC_STREAM_S stream;
    FY_S32 s32MilliSec;
}VDEC_IOC_SENDSTREAM_S;

typedef struct iocgetimage_t
{
    VIDEO_FRAME_INFO_S fameInfo;
    FY_S32 s32MilliSec;
}VDEC_IOC_GETIMAGE_S;


typedef struct iocgetUsrData_t
{
    VDEC_USERDATA_S usrData;
    FY_S32 s32MilliSec;
}VDEC_IOC_GETUSERDATA_S;

#define IOC_VDEC_BIND_CHAN                  _IOW(IOC_TYPE_VDEC,10,VDEC_CHN)
#define IOC_VDEC_UNBIND_CHAN                _IO(IOC_TYPE_VDEC,1)
#define IOC_VDEC_CREATE_CHAN                _IOW(IOC_TYPE_VDEC,0,fyVDEC_CHN_ATTR_S)
#define IOC_VDEC_DESTROY_CHAN               _IO(IOC_TYPE_VDEC,2)
#define IOC_VDEC_GET_CHAN_ATTR              _IOR(IOC_TYPE_VDEC,3,fyVDEC_CHN_ATTR_S)
#define IOC_VDEC_START_RECV_STREAM          _IO(IOC_TYPE_VDEC,7)
#define IOC_VDEC_STOP_RECV_STREAM           _IO(IOC_TYPE_VDEC,8)
#define IOC_VDEC_QUERY                      _IOR(IOC_TYPE_VDEC,6,fyVDEC_CHN_STAT_S)
#define IOC_VDEC_RESET_CHAN                 _IO(IOC_TYPE_VDEC,9)
#define IOC_VDEC_SET_CHAN_PARAM             _IOW(IOC_TYPE_VDEC,13,VDEC_CHN_PARAM_S)
#define IOC_VDEC_GET_CHAN_PARAM             _IOR(IOC_TYPE_VDEC,14,VDEC_CHN_PARAM_S)
#define IOC_VDEC_SET_PROTOCOL_PARAM         _IOW(IOC_TYPE_VDEC,15,VDEC_PRTCL_PARAM_S)
#define IOC_VDEC_GET_PROTOCOL_PARAM         _IOR(IOC_TYPE_VDEC,16,VDEC_PRTCL_PARAM_S)
#define IOC_VDEC_SEND_STREAM                _IOW(IOC_TYPE_VDEC,4,VDEC_IOC_SENDSTREAM_S)
#define IOC_VDEC_GET_IMAGE                  _IOWR(IOC_TYPE_VDEC,20,VDEC_IOC_GETIMAGE_S)
#define IOC_VDEC_RELEASE_IMAGE              _IOW(IOC_TYPE_VDEC,21, VIDEO_FRAME_INFO_S)
#define IOC_VDEC_GET_USER_DATA              _IOWR(IOC_TYPE_VDEC,17,VDEC_IOC_GETUSERDATA_S)
#define IOC_VDEC_RELEASE_USER_DATA          _IOW(IOC_TYPE_VDEC,19,VDEC_USERDATA_S)
#define IOC_VDEC_SET_ROTATE                 _IOW(IOC_TYPE_VDEC,29,ROTATE_E)
#define IOC_VDEC_GET_ROTATE                 _IOR(IOC_TYPE_VDEC,30,ROTATE_E)
#define IOC_VDEC_GET_CHAN_LUMA              _IOR(IOC_TYPE_VDEC,31,VDEC_CHN_LUM_S)
#define IOC_VDEC_SET_USER_PIC               _IOW(IOC_TYPE_VDEC,26,VIDEO_FRAME_INFO_S)
#define IOC_VDEC_ENABLE_USER_PIC            _IOW(IOC_TYPE_VDEC,27, FY_BOOL)
#define IOC_VDEC_DISABLE_USER_PIC           _IO(IOC_TYPE_VDEC,28)
#define IOC_VDEC_SET_DISPLAY_MODE           _IOW(IOC_TYPE_VDEC,32,VIDEO_DISPLAY_MODE_E)
#define IOC_VDEC_GET_DISPLAY_MODE           _IOR(IOC_TYPE_VDEC,33,VIDEO_DISPLAY_MODE_E)
#define IOC_VDEC_SET_CHAN_VBCNT             _IOW(IOC_TYPE_VDEC,34,FY_U32)
#define IOC_VDEC_GET_CHAN_VBCNT             _IOR(IOC_TYPE_VDEC,35,FY_U32)
#define IOC_VDEC_ATTACH_VBPOOL              _IOW(IOC_TYPE_VDEC,36,VDEC_CHN_POOL_S)
#define IOC_VDEC_DETACH_VBPOOL              _IO(IOC_TYPE_VDEC,37)
#define IOC_VDEC_SET_MOD_PARAM              _IOW(IOC_TYPE_VDEC,38,VDEC_MOD_PARAM_S)
#define IOC_VDEC_GET_MOD_PARAM              _IOR(IOC_TYPE_VDEC,39,VDEC_MOD_PARAM_S)
#define IOC_VDEC_SET_LOG_PARAM              _IOW(IOC_TYPE_VDEC,40,FY_U32)
#define IOC_VDEC_EXT                         FY_DRV_ADV_IOC(IOC_TYPE_VDEC)



#endif//__VDEC_DRV_IOC_H__
